version: "3.7"
services:
  service-microservice:
    container_name: service-microservice
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    env_file: ./.env
    volumes:
      - ./:/code
  postgres:
    image: postgis/postgis
    container_name: microservice-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=empty
      - POSTGRES_PASSWORD=empty
    env_file: ./.env

networks:
  core:
    external: true
    name: core